### ISSUE TITLE
Build process for dev branch

### ISSUE THREAD

**Issue by Seanny123** [ravichugh/sketch-n-sketch#133]
I was talking to Justin/Ravi and they told me all the cool things happening on the dev branch, so I wanted to try it out. However, each time I try to run `make` in `sketch-n-sketch/src` on the dev branch, it uses up all my 15 GB of RAM on my Ubuntu machine. Is there a new build process?

**Comment by brianhempel** [comment]
1. Replace your `elm-make` binary with [this one](http://people.cs.uchicago.edu/~brianhempel/faster-elm-make/x86-64/elm-make).

2. Remove the `src/elm-stuff` directory before building the first time (this will ensure the build system grabs our custom standard library).

Let me know if the above doesn't work.

**Comment by ravichugh** [comment]
I just posted a v0.7.0 release (tagged last month):

  http://ravichugh.github.io/sketch-n-sketch/releases/v0.7.0/index.html

This version includes an Elm-like source level syntax, support for generating HTML output, and a new updated algorithm for making changes to HTML output. We haven't linked to it yet from the releases page yet, because there are several things that need to be cleaned up and fixed to get some basic SVG functionality from before working (sometime in the coming weeks/months).

So if you're not able to get the build to work, you may want to play with this version a bit.

**Comment by Seanny123** [comment]
This still works!
