### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Seanny123** [ravichugh/sketch-n-sketch#93]
I was trying to get started adding text to the things you can manipulate in sketch-n-sketch. I was also hoping this would motivate me to learn about compilers and functional programming via Elm. I can't figure out how to build it locally. What I've done:

1. Successfully ran `make` in `src` directory
2. Installed `fswatch`
3. Tried to run `.\makewatch`

What else am I supposed to do? Also, is it okay I'm using Elm 18.0?

**Comment by Seanny123** [comment]
That worked for me! Thanks, I'll add those instructions to the README. I think I might need to do a MOOC on compilers before I can help you with that stack bug that I'm still experiencing. However, let me know when you've got that sorted out so I can add text features to the master branch.

**Comment by brianhempel** [comment]
The stack problem is our fault (mainly the parser's problem), but it's not high on our priority list to fix because you can dodge it by increasing the browser stack size. If you're on a Mac you can use the `chrome_super` script that Justin mentioned—just make sure that Chrome is not already open. On Linux you can probably just open Chrome from the Terminal with the added argument `--js-flags="--stack-size=8192"`.

Firefox's default stack size is large enough (on a Mac at least). However because of a bug in Firefox in the last couple of releases I've had to downgrade to 50.1.0 to avoid Firefox outright crashing. Download here and then don't restart firefox after opening :smile: https://ftp.mozilla.org/pub/firefox/releases/50.1.0/

If you get it running and want some direction on where to go in the code, let us know. You may be interested in the techniques used in [this paper](https://users.soe.ucsc.edu/~cschuster/live16/html/) for tracking string origins.

**Comment by Seanny123** [comment]
Even with a stack size of 10000, I can't get it to work with Chrome on
either Windows or Linux. Being a pleb who doesn't own a Mac means fixing
this has a bit more priority for me. Consequently, if you could show me the
specific test case where it breaks, that would be super awesome.

**Comment by jlubi333** [comment]
Fixing #84 should fix this issue, so I will migrate this issue to that thread.
