### ISSUE TITLE
Sketch-n-Sketch doesn't load in Firefox

### ISSUE THREAD

**Issue by jlubi333** [ravichugh/sketch-n-sketch#99]

**Comment by brianhempel** [comment]
It's a Firefox bug, broken since the end of January I think. Surprised they haven't fixed it yet. I wonder if it's a known bug. Version 50.1.0 is the last version that works, which you can find here: https://ftp.mozilla.org/pub/firefox/releases/50.1.0/

Don't destroy the download though if you use FF, because FF will auto-update when you close it so you have to keep blowing away the auto-updated version.

**Comment by jlubi333** [comment]
It works for me in Firefox 54.0.1 (Mac) now! Can anyone else confirm this?

**Comment by ravichugh** [comment]
Working for me too!
